name: Deploy Laravel on top of frankenphp

on:
    push:
        branches:
        - filament
    pull_request:
        branches:
        - filament

jobs:
  php-security-check:
    name: PHP Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
                  - name: Upload result to GitHub Code Scanning
                  uses: github/codeql-action/upload-sarif@v2
                  with:
                    sarif_file: snyk.sarif

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pbl-filament:latest .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: your/image-to-test
          args: --file=Dockerfile
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pbl-filament:latest
